# Generated by Django 5.1.7 on 2025-05-04 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_20250501_0335'),
        ('accounts', '0008_alter_transaction_category'),
    ]

    operations = [
    ]
