# Generated by Django 5.1.7 on 2026-04-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20250504_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='logo_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
