# Generated by Django 5.1.7 on 2026-04-07 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_bill_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='plaid_account_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='plaid_item_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='transaction',
            name='plaid_transaction_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='PlaidItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=500)),
                ('item_id', models.CharField(max_length=200, unique=True)),
                ('institution_id', models.CharField(blank=True, default='', max_length=200)),
                ('institution_name', models.CharField(blank=True, default='Connected Bank', max_length=200)),
                ('cursor', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plaid_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
